### ISSUE TITLE
Other implementation

### ISSUE THREAD

**Issue by cyrusmsk** [gdamore/tree-sitter-d#13]
Thanks for your work!

Just wondering that there is also a project https://github.com/CyberShadow/tree-sitter-d

is your project evolve this realisation? Or how they comparable? And is it possible to boost the quality if unite the effort and power from several ports into one project?

**Comment by gdamore** [comment]
I started by looking at that work. It was too busted to be usable - and the author had indicated he was not working on it any longer.  Personally I think the approach of starting with libdparse is a doomed effort as the even that project is out of synch with the spec. 

Having said that I don’t feel any need for personal ownership here and am happy to collaborate - if my work can improve that other version or if we want to try to fold the work there I am happy either way. I just want something that pragmatically works. 

This was as much a learning effort as an effort to solve real problems. In that regard it was very helpful to me. 

I hope that the next work I have done here can be useful for others - whether by helping inform improvements to other projects or acting as a new foundation for further work does not matter to me.

**Comment by gdamore** [comment]
To be further clear - for this particular project I would be happy to hand the reins off to other parties who were committed to improving the work.  I really want this work to go further and I really want D to have an officially accepted grammar for tree sitter. Anything that furthers that goal is IMO worthwhile. 

A secondary but also important desire is to have an actual functional machine readable grammar for the language. Relying solely on DMD behavior as a sort of "spec" for the language is IMO both limiting and unfortunate.

**Comment by gdamore** [comment]
This is a question, so I'm going to close it for now, as there is nothing actionable.

I'm probably going to try to see if I can hand this repo off to the tree-sitter org, or possibly to the D language org.  I don't really want to own it, to be completely frank.
