### ISSUE TITLE
Bad type highlighting in helix 

### ISSUE THREAD

**Issue by MightyPrinny** [gdamore/tree-sitter-d#21]
**The problem**
User types aren't highlighted in the helix editor with the current highlights.scm

**To Reproduce**
Open d file in helix.

**Expected behavior**
User defined types should be highlighted as types

**Fix**
As a workaround I made these changes to the highlights.scm for helix where `@function` was used
```
(call_expression (identifier) @function)
(call_expression (type (identifier) @function))
(call_expression (type (template_instance (identifier) @function)))
(call_expression (type (template_instance (template_arguments (identifier) @type))))
(type (identifier) @type)
```
I don't understand how tree sitter or the highlighting system works so I'm posting it so you can decide if it's good enough for now, the highlighting in general isn't as rich as in other languages, but for me personally this is one of the most important things to have highlighted.

**Comment by gdamore** [comment]
I've made some changes to the main highlights.scm.  I'm not using Helix right now, so I can't easily assess if those changes are good or not.

**Comment by gdamore** [comment]
@MightyPrinny can you tell me if the changes in the highlights.scm are good?  I don't maintain the helix plugin.

**Comment by MightyPrinny** [comment]
I don't think so, I tried the current highlights.scm in neovim and now functions look like types and types aren't highlighted in pointer declarations.

**Comment by gdamore** [comment]
I'm not sure if neovim's queries are compatible...  I need to look into this.

**Comment by gdamore** [comment]
The grammar for call_expression is this:

```
    call_expression: ($) =>
      prec.left(
        choice(
          seq($._unary_expr, $.named_arguments),
          seq($.type, $.named_arguments),
        ),
      ),
```

This isn't particularly satisfying.

Realistically, we'd like to call out uer defined types.  But it's also the case that we basically have no way to distinguish between constructors and bare functions.  (UFCS also makes this a bit harder.)
