### ISSUE TITLE
Q: How do you actually use the grammar?

### ISSUE THREAD

**Issue by snosov1** [gdamore/tree-sitter-d#25]
Hello!

Sorry for the stupid question, but after installing - how do I actually use the grammar? The online tutorials mention the language major mode needs to be implemented with tree-sitter in mind (and the current convention is that for each `<lang>-mode` people would implement `<lang>-ts-mode`). Some languages have these modes in MELPA. But others including D (which, I guess, you can explain by relatively low popularity - but even Python don't seem to have it). There's also conflicting pieces of information about built-in tree-sitter (the one I have) and external packages (that seem to suggest using built-in instead).

Can you, please, shed the light on it? Maybe, point to a relevant tutorial or smth?

**Comment by dejlek** [comment]
I would like to know that too. :) Asked on IRC earlier today - nobody knew the answer. I've seen helix and neovim (can) use tree-sitter, but I could not find information how, so it would be really nice if someone writes a section in the REDME about how to use it...

**Comment by snosov1** [comment]
Vladimir @CyberShadow, maybe, you have some pointers?

**Comment by gdamore** [comment]
The details of the manner in which you use the grammar are totally dependent upon the editor your use.  If you're using emacs (it sounds like that), then you'll need to read the documentation.

Typically in addition to the grammar itself you need to pick up the query list.  One thing I've noticed recently is that we weren't doing the best job of exposing the query list in a discoverable way.

**Comment by snosov1** [comment]
Yeah, my question is about Emacs, specifically. From your answer I get that you use something else and have no experience using it with Emacs, right?

**Comment by gdamore** [comment]
Correct.  I use this grammar with Nova, and I've tested it with Helix, and I know others have used it with Lapce and with Vim.

**Comment by gdamore** [comment]
I've added some metadata that might help.  I don't know how this works with emacs, but if you've followed instructions try again.

The following might help:

https://www.masteringemacs.org/article/how-to-get-started-tree-sitter

**Comment by snosov1** [comment]
Got it, thanks! Yeah, there are some docs that introduce tree-sitter in Emacs - still, I can't seem to find a way other than "let's hack some elisp code myself" which feels wrong (like, am I the first/only one trying to use it?!). Anyway, thanks - I'll keep looking!
