### ISSUE TITLE
Support Hexadecimal String Literals

### ISSUE THREAD

**Issue by nordlow** [gdamore/tree-sitter-d#28]
Examples of usage are at https://dlang.org/changelog/2.108.0.html#dmd.hexstring-cast.

**Comment by gdamore** [comment]
Looks reasonable, although DMD 2.108 is not *yet* released.  I'll probably trail the release a little bit on these new extensions.

**Comment by gdamore** [comment]
So I think hex strings are much older than 2.108, but 2.108 added the suffix.  Somehow this was missed in my original work.
