### ISSUE TITLE
(Member) function attributes should be placed under `function_declaration`

### ISSUE THREAD

**Issue by nordlow** [gdamore/tree-sitter-d#38]
Currently `property` in

```d
void foo() pure @property;
```

is put in 

```
(at_attribute (identifier))
```

when it should be

```
(function_declaration (member_function_attribute (at_attribute (identifier))))
```

to conform with `pure` being put in

```
(function_declaration (member_function_attribute (pure)))
```

.

**Comment by gdamore** [comment]
I'm not sure the grammar is completely clear here.  I'll have a look -- but its possible that the grammar is ambiguous in this case (there are other cases where you need semantic information that isn't available in the syntax tree.  This *might* be one of them.)

**Comment by gdamore** [comment]
I tested this, and it seems right already:

```
(source_file
  (function_declaration
    (type
      (void))
    (identifier)
    (parameters)
    (member_function_attribute
      (pure))
    (member_function_attribute
      (at_attribute
        (identifier)))
    (function_body)))
```
