### ISSUE TITLE
Easier/cleaner way to write tree-sitter grammar

### ISSUE THREAD

**Issue by mingodad** [gdamore/tree-sitter-d#43]
Here https://mingodad.github.io/lua-wasm-playground/ there is an easier/cleaner way to write tree-sitter grammars like `D` (select `Tree-sitter-ebnf-generator-D` from `Examples` then click `Run` to see a full commented out `grammar.js` from the `EBNF` variant describng the grammar in `
Input Text (arg[1])`).

I hope it can be helpful !

**Comment by gdamore** [comment]
So... that playground is actually *using* this tree-sitter grammar ... there is no other EBNF source for D, which is a source of some frustration on my part. 

So we cannot *use* that as a source since it would just be a kind of self-reference lol!

**Comment by mingodad** [comment]
Hello @gdamore here is another grammar for `D` https://github.com/dlang-community/libdparse/issues/522
